name: Build and Publish Dev Image

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  DEV_IMAGE_NAME: ${{ github.repository_owner }}/c4ignite-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine tag name
        id: tag
        run: |
          DATE_TAG=$(date -u +"%d-%m.%y.%H%M.%S")
          echo "tag-name=${DATE_TAG}" >> "$GITHUB_OUTPUT"

      - name: Build and push dev image
        run: |
          TAG_NAME="${{ steps.tag.outputs.tag-name }}"
          IMAGE="${REGISTRY}/${DEV_IMAGE_NAME}"
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -f docker/dev/php/Dockerfile \
            -t "${IMAGE}:${TAG_NAME}" \
            -t "${IMAGE}:latest" \
            --push \
            .
