name: Build and Publish Dev Image

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  DEV_IMAGE_NAME: ${{ github.repository_owner }}/c4ignite-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push dev image
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          IMAGE="${REGISTRY}/${DEV_IMAGE_NAME}:${TAG_NAME}"
          docker build -f docker/dev/php/Dockerfile -t "${IMAGE}" .
          docker tag "${IMAGE}" "${REGISTRY}/${DEV_IMAGE_NAME}:latest"
          docker push "${IMAGE}"
          docker push "${REGISTRY}/${DEV_IMAGE_NAME}:latest"
