name: CI

on:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run Python unit tests
        run: python -m unittest discover -s tests/python

  smoke-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install bats
        run: |
          sudo apt-get update
          sudo apt-get install -y bats

      - name: Run CLI smoke tests
        env:
          C4IGNITE_ALLOW_HOST_PYTHON: "1"
          C4IGNITE_SKIP_DOCKER_FIX: "1"
        run: bats tests/cli
